comments/urls.py
from django.urls import path
import comments.views as views

app_name = "comments"

urlpatterns = [
    path("", views.home, name="home"),
    path("about_me", views.about_me, name="about-me"),
    path("contact_me", views.contact_me, name="contact-me"),
    path("comments", views.comments_page, name="comments"),
]

comments_backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [path("admin/", admin.site.urls), path("", include("comments.urls"))]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

comments/models.py
from django.db import models


# Create your models here.
class Comment(models.Model):
    name = models.CharField(blank=False, max_length=150)
    comment = models.TextField(blank=False, max_length=720)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)

comments/forms.py
from django import forms
from .models import Comment


class AddComment(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["name", "comment"]

comments/views.py
from django.shortcuts import render
from .forms import AddComment
from .models import Comment



# Create your views here.
def home(request):
    return render(request, "comments/index.html")


def about_me(request):
    return render(request, "comments/about_me.html")


def comments_page(request):
    comments = Comment.objects.all()
    if request.method == "POST":
        form = AddComment(request.POST)
        if form.is_valid():
            form.save()
            form = AddComment()
            return render(
                request,
                "comments/comments_page.html",
                context={"form": form, "comments": comments},
            )

    else:
        form = AddComment()
    return render(
        request,
        "comments/comments_page.html",
        context={"form": form, "comments": comments},
    )


def contact_me(request):
    return render(request, "comments/contact_me.html")

comments/templates/comments/about_me.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Personal portfolio</title>
    <link href="{% static 'comments/style.css'%}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    <h1>ABOUT ME</h1>
    <nav>
      <a href="{% url 'comments:home' %}"><button>Home</button></a>
      <a href="{% url 'comments:about-me'%}"><button>About me</button></a>
      <a href="{% url 'comments:contact-me'%}"><button>Contact me</button></a>
      <a href="{% url 'comments:comments'%}"><button>Discussion</button></a>
  </nav>

  <table>
    <tr>
      <td>
        <div class="w3-content" style="width:800px;margin-top:46px; height: 300px; margin-top: -200px;">
          <div class="mySlides w3-display-container w3-center">
            <img src="{% static 'comments/St.Fr.Ch_Sanjay_vedant1.JPG' %}" style="width:100%">
            <div class="w3-display-bottommiddle w3-container w3-text-white w3-padding-32 w3-hide-small">
              <h3>Roadtrip</h3>
              <center>
              <p style="color: aliceblue;">Me with my dad on a roadtrip</p>    
              </center>
            </div>
          </div>
          <div class="mySlides w3-display-container w3-center">
            <img src="{% static 'comments/vedant_2.jpg' %}" style="width:100%">
            <div class="w3-display-bottommiddle w3-container w3-text-white w3-padding-32 w3-hide-small">
              <h3>Jaipur</h3>
              <center>
              <p style="color: aliceblue;">My sister, me, dad, and my grandparents in Jaipur</p>      
              </center> 
            </div>
          </div>
          <div class="mySlides w3-display-container w3-center">
            <img src="{% static 'comments/St.FrChurch_Isha_vedant_sangeeta3.JPG' %}" style="width:100%">
            <div class="w3-display-bottommiddle w3-container w3-text-white w3-padding-32 w3-hide-small">
              <h3>Red fort</h3>
              <center>
              <p style="color: aliceblue;">Me posing in style at the red fort</p>      
              </center> 
            </div>
          </div>

      </td>
      <td>
        <p style="color: aliceblue; margin-top: 75px; margin-left: 20px; margin-right: 20px;">My name is Vedant Sindhwani, and I am currently a student at BITS Pilani College, hailing from the vibrant city of Delhi.<br>Pursuing my passion for technology, I am studying Computer Science, constantly immersing myself in the ever-evolving world of coding, algorithms, and software development.<br>

          From an early age, I discovered my affinity for tinkering and experimenting with various technologies, always curious to understand how things work.<br> This innate curiosity has fueled my love for learning, as I am constantly seeking new knowledge and expanding my skillset. The thrill of discovering and mastering new concepts is what drives me to push the boundaries of my understanding.<br>
          
          When I'm not engrossed in technology, you'll likely find me on the tennis court or swimming in the pool. Sports have always been an essential part of my life, offering a much-needed balance to the mental challenges of computer science. The focus, discipline, and camaraderie found in these activities complement my academic pursuits, allowing me to stay grounded and refreshed.
          
          <br>One aspect that sets me apart is my passion for solving problems through creativity and ingenuity. I relish the opportunity to tackle complex challenges and find innovative solutions. Whether it's creating an efficient algorithm, designing a user-friendly interface, or devising a clever workaround, I thrive on the satisfaction of turning ideas into reality.
          
          <br>Beyond my academic and technological pursuits, my heart lies with my family. I am fortunate to live with my sister, parents, and grandparents, who have always been a source of love, support, and inspiration in my life. Their unwavering encouragement and belief in my abilities have shaped me into the person I am today.
          
          In conclusion, I am a curious and enthusiastic student at BITS Pilani College, passionate about computer science, technology, and the power of creativity. With a love for learning, a knack for problem-solving, and a strong bond with my family, I am ready to embrace new opportunities, contribute to the world of technology, and make a positive impact wherever I go.</p>
      </td>
    </tr>
  </table>

  

    <script>
        var myIndex = 0;
        carousel();
        
        function carousel() {
          var i;
          var x = document.getElementsByClassName("mySlides");
          for (i = 0; i < x.length; i++) {
            x[i].style.display = "none";  
          }
          myIndex++;
          if (myIndex > x.length) {myIndex = 1}    
          x[myIndex-1].style.display = "block";  
          setTimeout(carousel, 4000);    
        }
        </script>
        

</body>

</html>

comments/templates/comments/comments_page.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Personal portfolio</title>
    <link href="{% static 'comments/style.css'%}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    <h1>DISCUSSION</h1>
    <nav>
        <a href="{% url 'comments:home' %}"><button>Home</button></a>
        <a href="{% url 'comments:about-me'%}"><button>About me</button></a>
        <a href="{% url 'comments:contact-me'%}"><button>Contact me</button></a>
        <a href="{% url 'comments:comments'%}"><button>Discussion</button></a>
    </nav>
    <center>
    <form method="POST" title="type your comment in the box!"
        style="margin-top: 25px; margin-left: 20px; width: 400px; padding-bottom: 25px; border-radius: 16px"
        class="comment_button">
        {%csrf_token%}
        <h3 style="margin: 5px;">
            Add a comment: <br>
        </h3>
        <input size="50" placeholder="Enter your name here" name="name" style="margin-bottom: 5px;">
        <input size="50" height="500px" name="comment" placeholder="Enter your comment here">
        <br>
        <input type="submit"
            style="border-radius: 16px; padding: 10px; font-size: 16px; margin-top: 5px; margin-left: 350px;"
            class="submit_button" value="Add comment">
        </button>
    </form>
    </center>
    <br>

    <table style="margin-top: 20px; color:aliceblue">
        <tr>
            <h2 style="color: aliceblue;">
                USER COMMENTS:
            </h2>
        </tr>
    </table>
        
    {% for comment in comments %}
        <table id="comments_paragraph"
        style="margin-top: 25px; margin-left: 15px; background-color: rgb(228, 244, 235);padding: 10px;width: 1000px; border-radius: 10px; ">
            
            <tr>
                <td>
                    {{comment.name}}
                </td>
                <td style="text-align: right;">
                    {{comment.created_at}}<br>
                </td>
            </tr>
            <tr>
                <td>{{comment.comment}}</td>
                
            </tr>
        </table>
        {%endfor%}
</body>

</html>

comments/templates/comments/contact_me.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Personal portfolio</title>
    <link href="{% static 'comments/style.css'%}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    <h1>CONTACT ME</h1>
    <nav>
        <a href="{% url 'comments:home' %}"><button>Home</button></a>
        <a href="{% url 'comments:about-me'%}"><button>About me</button></a>
        <a href="{% url 'comments:contact-me'%}"><button>Contact me</button></a>
        <a href="{% url 'comments:comments'%}"><button>Discussion</button></a>
    </nav>
    <p
        style="margin-top: 25px; margin-left: 15px; background-color: rgb(228, 244, 235);padding: 10px; width: 500px; border-radius: 10px;">
        My contact information:<br>
        Name: Vedant Sindhwani<br>
        Phone no: 9958439673<br>
        Email: vedant.sindhwani@gmail.com<br>
        Institute email: f20220055@pilani.bits-pilani.ac.in<br>
        Current address: Room number 2140, Gandhi Bhavan
    </p>
    <h3>
        Want me to contact you? Let me know your contact details!
    </h3>
    <center>
        <table
            style="margin-top: 25px; margin-left: 15px; background-color: rgb(228, 244, 235);padding: 10px; width: 500px; border-radius: 10px; font-family: 'Courier New', Courier, monospace;">
            <tr>
                <td>
                    Enter your name:
                </td>
                <td>
                    <input id="name_input">
                </td>
            </tr>
            <tr>
                <td>
                    Enter your phone number:
                </td>
                <td>
                    <input id="number_input">
                </td>
            </tr>
            <tr>
                <td>
                    Enter your email address:
                </td>
                <td>
                    <input id="email_input">
                </td>
            </tr>
            <tr>
                <td>
                    Enter your address:
                </td>
                <td>
                    <input id="address_input">
                </td>
            </tr>
            <tr>
                <td>
                    Enter your message:
                </td>
                <td>
                    <input id="message">
                </td>
            </tr>
        </table>
        <button style="border-radius: 16px; padding: 10px; font-size: 16px; margin-top: 12px;" class="submit_button"
            onclick="collectinfo()">
            Submit details
        </button>
    </center>
    <script>
        function collectinfo() {
            var name = document.getElementById("name_input").value;
            var number = document.getElementById("number_input").value;
            var email = document.getElementById("email_input").value;
            var address = document.getElementById("address_input").value;

        }
    </script>
</body>

</html>

comments/templates/comments/index.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Personal portfolio</title>
    <link href="{% static 'comments/style.css'%}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    <h1>HOME PAGE</h1>
    <nav>
        <a href="{% url 'comments:home' %}"><button>Home</button></a>
        <a href="{% url 'comments:about-me'%}"><button>About me</button></a>
        <a href="{% url 'comments:contact-me'%}"><button>Contact me</button></a>
        <a href="{% url 'comments:comments'%}"><button>Discussion</button></a>
    </nav>
    <table>
        <tr>
            <td>
                <table>
                    <tr>
                        <h2
                            style="margin-top: 30px; margin-left: 50px; background-color: rgb(228, 244, 235); padding: 10px;border-radius: 10px; margin-bottom: 10px; width: 200px; font-weight: 400; font-size: 30;">
                            INTRODUCTION
                        </h2>
                    </tr>
                    <tr>
                        <p
                            style="margin-top: 25px; margin-left: 15px; background-color: rgb(228, 244, 235);padding: 10px;width: 1000px; border-radius: 10px;">
                            Greetings!

                            Welcome to my world of curiosity, innovation, and a deep passion for technology. 
                            I am thrilled to introduce myself as Vedant Sindhwani, a student at BITS Pilani College, Delhi, where I am pursuing my studies in Computer Science. 
                            With an insatiable desire to learn, a penchant for tinkering, and a love for solving problems, I embark on an exciting journey of discovery and growth.
                            At BITS Pilani College, I am immersed in a stimulating academic environment where I am continuously challenged and encouraged to explore the limitless possibilities of technology. 
                            The curriculum, coupled with the guidance of experienced mentors, has equipped me with a solid foundation in programming, algorithms, and software development. 
                            This knowledge forms the bedrock on which I build my skills, ever eager to expand my horizons and stay at the forefront of technological advancements.
                            As I embark on this journey, armed with a thirst for knowledge, an insatiable curiosity, and an unwavering dedication to my craft, I am excited to see where the path of technology will take me.
                            Join me as I navigate through the realm of computer science, learning, creating, and making a difference in the world, one innovation at a time.
                    </tr>
                </table>
            </td>
            <td>
                <img src="{% static 'comments/profile_pic.jpg' %}" alt="Me in agra"
                    style="width: 400px;height: 400px;margin-left: 60px;margin-right: 60px;margin-top: 60px; border-radius: 50%;">
            </td>
        </tr>
    </table>
    <table>
        <tr>
            <td>
                <p style="font-weight: 400; font-size: 30; margin-left: 50px; color:rgb(228, 244, 235)">connect with me
                    at:</p>
            </td>
            <td>
                <a href="https://twitter.com/sindhwanivedant" class="fa fa-twitter"></a>
            </td>
            <td>
                <a href="https://www.instagram.com/vedant_sindhwani/" class="fa fa-instagram"></a>
            </td>
            <td>
                <a href="https://www.facebook.com/vedant.sindhwani.1" class="fa fa-facebook"></a>
            </td>
            <td>
                <a href="https://www.linkedin.com/in/vedant-sindhwani-93720b145/" class="fa fa-linkedin"></a>
            </td>
        </tr>
    </table>
</body>

</html>